/**
 * OLLCP recognition data accessor. The JSON is generated by
 * scripts/generate-ollcp-trainer-data.mjs (57 OLLs × 6 variants + recognition cues + priority +
 * real Kociemba scrambles). Imported directly like the recognition trainer imports its JSON.
 */
import raw from '../../../../public/trainer/ollcp-recognition.json';
import type {OllcpData, OllcpOll} from './types';

export const OLLCP_DATA = raw as unknown as OllcpData;

/** Ordered OLL numbers 1..57 (as strings) present in the data. */
export const OLL_NUMBERS: string[] = Object.keys(OLLCP_DATA).sort((a, b) => Number(a) - Number(b));

export function getOll(ollNum: string): OllcpOll | undefined {
	return OLLCP_DATA[ollNum];
}
