/**
 * OLL/PLL case identification — exact port of cstimer cubeutil.js.
 *
 * Source: Reference/cstimer-master/src/js/lib/cubeutil.js
 *   - identPLL: searchCaseByPattern(facelet, ollMask, pllPatterns)
 *   - identOLL: searchCaseByPattern(facelet, f2lMask, ollPatterns)
 *
 * cstimer's 24-cube-rotation cubeRots table + masks + patterns dumped at build-time
 * via scripts/dump-cstimer-rotations.mjs from cstimer source
 * (shared/data/cstimer_ll_engine.json).
 *
 * Runtime only performs pure string operations — no cubejs/cubing.js dependency.
 * Algorithm is color-agnostic (toEqus equivalence classes) — user's cube
 * orientation or cross face doesn't matter.
 */

import engine from '../../data/cstimer_ll_engine.json';

interface CaseMatch {
	case: string;
	key: string;
}

const CUBE_ROTS: number[][] = (engine as any).cubeRots;
const OLL_MASK: number[][] = (engine as any).masks.ollMask;
const F2L_MASK: number[][] = (engine as any).masks.f2lMask;
const PLL_PATTERNS: number[][][] = (engine as any).pllPatterns;
const OLL_PATTERNS: number[][][] = (engine as any).ollPatterns;
const PLL_INDEX_TO_KEY: Array<string | null> = (engine as any).pllIndexToKey;
const OLL_INDEX_TO_KEY: Array<string | null> = (engine as any).ollIndexToKey;
const PLL_CASE_NAMES: string[] = (engine as any).pllCaseNames;
const OLL_CASE_NAMES: string[] = (engine as any).ollCaseNames;

// Corner-case sets (COLL for two-look CFOP, CMLL for Roux). Both are generated by
// scripts/dump-cstimer-rotations.mjs from cstimer's coll_map; they differ only in
// how the last-layer EDGES are filled: COLL pins them solved, CMLL leaves them
// wildcard because Roux fixes edges later in LSE.
//
// Regenerating the dump is a separate step, so every lookup degrades to "no match"
// rather than throwing when a set is absent from the JSON.
const EOLL_MASK: number[][] | null = (engine as any).masks?.eollMask ?? null;
const ROUX_SB_MASK: number[][] | null = (engine as any).masks?.rouxSbMask ?? null;
const COLL_PATTERNS: number[][][] = (engine as any).collPatterns ?? [];
const CMLL_PATTERNS: number[][][] = (engine as any).cmllPatterns ?? [];
const COLL_INDEX_TO_KEY: Array<string | null> = (engine as any).collIndexToKey ?? [];
const COLL_CASE_NAMES: string[] = (engine as any).collCaseNames ?? [];

// ZBLL — the full 493-case one-look last layer, for solvers who reach it with
// edges already oriented (ZZ, or CFOP users drilling ZBLL). Generated from
// cstimer's genZBLLMap via scripts/dump-cstimer-rotations.mjs.
const ZBLL_PATTERNS: number[][][] = (engine as any).zbllPatterns ?? [];
const ZBLL_CASE_NAMES: string[] = (engine as any).zbllCaseNames ?? [];

/**
 * cstimer cubeutil.js solvedProgress (facelet variant) port:
 *   Rotates facelet by rotIdx and checks for each equivalence class in mask
 *   whether the stickers are the same color. If all are, return "solved".
 */
function solvedProgress(facelet: string, rotIdx: number, mask: number[][]): boolean {
	const cubeRot = CUBE_ROTS[rotIdx];
	for (const equ of mask) {
		const col = facelet[cubeRot[equ[0]]];
		for (let j = 1; j < equ.length; j++) {
			if (facelet[cubeRot[equ[j]]] !== col) return false;
		}
	}
	return true;
}

/**
 * cstimer searchCaseByPattern port:
 *   1. Find rotations that are solved according to baseMask (within 24 cube symmetries)
 *   2. For each pattern, search for matches in rotations from chkList
 *   3. Return index of first matching pattern, or -1 if none
 */
function searchCaseByPattern(
	facelet: string,
	baseMask: number[][],
	patterns: number[][][]
): number {
	const chkList: number[] = [];
	for (let a = 0; a < 24; a++) {
		if (solvedProgress(facelet, a, baseMask)) chkList.push(a);
	}
	for (let i = 0; i < patterns.length; i++) {
		for (const r of chkList) {
			if (solvedProgress(facelet, r, patterns[i])) return i;
		}
	}
	return -1;
}

export function getMatchingOLLState(facelet54: string, _crossFace?: string): CaseMatch | null {
	if (!facelet54 || facelet54.length !== 54) return null;
	const idx = searchCaseByPattern(facelet54, F2L_MASK, OLL_PATTERNS);
	if (idx < 0) return null;
	const key = OLL_INDEX_TO_KEY[idx];
	if (!key) return null; // skip case or no mapping
	return { case: OLL_CASE_NAMES[idx] || key, key };
}

export function getMatchingPLLState(facelet54: string, _crossFace?: string): CaseMatch | null {
	if (!facelet54 || facelet54.length !== 54) return null;
	const idx = searchCaseByPattern(facelet54, OLL_MASK, PLL_PATTERNS);
	if (idx < 0 || idx >= 21) return null; // index 21 = skip
	const key = PLL_INDEX_TO_KEY[idx];
	if (!key) return null;
	return { case: PLL_CASE_NAMES[idx] || key, key };
}

/**
 * COLL — last layer corners recognized once edges are already oriented.
 * Base mask is EOLL: the search only considers orientations where the LL edges
 * read as oriented, which is the state a two-look solver is in before CP.
 */
export function getMatchingCOLLState(facelet54: string): CaseMatch | null {
	if (!facelet54 || facelet54.length !== 54) return null;
	if (!EOLL_MASK || COLL_PATTERNS.length === 0) return null;
	const idx = searchCaseByPattern(facelet54, EOLL_MASK, COLL_PATTERNS);
	if (idx < 0) return null;
	const name = COLL_CASE_NAMES[idx];
	// The case is recognized either way. Our algorithm library covers only part
	// of this set, so when there is no local key we still report the case under
	// its standard name rather than throwing the recognition away.
	const key = COLL_INDEX_TO_KEY[idx] || name;
	if (!key) return null;
	return { case: name || key, key };
}

/**
 * CMLL — the same 42 corner cases as COLL, but recognized while the last layer
 * edges are still scrambled, so the patterns leave edges as wildcards and the
 * base mask is Roux's second block rather than EOLL.
 */
export function getMatchingCMLLState(facelet54: string): CaseMatch | null {
	if (!facelet54 || facelet54.length !== 54) return null;
	if (!ROUX_SB_MASK || CMLL_PATTERNS.length === 0) return null;
	const idx = searchCaseByPattern(facelet54, ROUX_SB_MASK, CMLL_PATTERNS);
	if (idx < 0) return null;
	const name = COLL_CASE_NAMES[idx];
	// The case is recognized either way. Our algorithm library covers only part
	// of this set, so when there is no local key we still report the case under
	// its standard name rather than throwing the recognition away.
	const key = COLL_INDEX_TO_KEY[idx] || name;
	if (!key) return null;
	return { case: name || key, key };
}

/**
 * ZBLL — port of cstimer identZBLL. Base mask is EOLL, matching cstimer: the
 * search only considers orientations where the last-layer edges read as oriented,
 * which is precisely the state a one-look ZBLL is performed from.
 */
export function getMatchingZBLLState(facelet54: string): CaseMatch | null {
	if (!facelet54 || facelet54.length !== 54) return null;
	if (!EOLL_MASK || ZBLL_PATTERNS.length === 0) return null;
	const idx = searchCaseByPattern(facelet54, EOLL_MASK, ZBLL_PATTERNS);
	if (idx < 0) return null;
	const name = ZBLL_CASE_NAMES[idx];
	if (!name) return null;
	// We carry no local ZBLL algorithm library, so the standard case name doubles
	// as the key — the same convention used for unmapped CMLL cases.
	return { case: name, key: name };
}

// Backward compatibility with old API (initLLStates was called in old code, no-op).
export function initLLStates() {
	void CUBE_ROTS;
}
