// WCA recognized countries + continents. Data ported from the WCA Regulations
// static data (worldcubeassociation.org: lib/static_data/countries.real.json +
// continents.json). Single source of truth for the record-radar region picker
// (client) and record scope matching (server). Keep dependency-free (shared/).

// The 17 official WCA events, in canonical display order. Only these can appear
// in a competition's event_ids and are the valid targets for a record watch.
export const WCA_EVENT_IDS: string[] = [
	"333",
	"222",
	"444",
	"555",
	"666",
	"777",
	"333bf",
	"333fm",
	"333oh",
	"clock",
	"minx",
	"pyram",
	"skewb",
	"sq1",
	"444bf",
	"555bf",
	"333mbf",
];

export interface WcaCountry {
	iso2: string;
	name: string;
	continentId: string;
}

export interface WcaContinent {
	id: string;
	name: string;
}

// The 6 real WCA continents (excludes the fictional _Multiple Continents).
export const WCA_CONTINENTS: WcaContinent[] = [
	{id: "_Africa", name: "Africa"},
	{id: "_Asia", name: "Asia"},
	{id: "_Europe", name: "Europe"},
	{id: "_North America", name: "North America"},
	{id: "_Oceania", name: "Oceania"},
	{id: "_South America", name: "South America"},
];

export const WCA_COUNTRIES: WcaCountry[] = [
	{iso2: "AF", name: "Afghanistan", continentId: "_Asia"},
	{iso2: "AL", name: "Albania", continentId: "_Europe"},
	{iso2: "DZ", name: "Algeria", continentId: "_Africa"},
	{iso2: "AD", name: "Andorra", continentId: "_Europe"},
	{iso2: "AO", name: "Angola", continentId: "_Africa"},
	{iso2: "AG", name: "Antigua and Barbuda", continentId: "_North America"},
	{iso2: "AR", name: "Argentina", continentId: "_South America"},
	{iso2: "AM", name: "Armenia", continentId: "_Europe"},
	{iso2: "AU", name: "Australia", continentId: "_Oceania"},
	{iso2: "AT", name: "Austria", continentId: "_Europe"},
	{iso2: "AZ", name: "Azerbaijan", continentId: "_Europe"},
	{iso2: "BS", name: "Bahamas", continentId: "_North America"},
	{iso2: "BH", name: "Bahrain", continentId: "_Asia"},
	{iso2: "BD", name: "Bangladesh", continentId: "_Asia"},
	{iso2: "BB", name: "Barbados", continentId: "_North America"},
	{iso2: "BY", name: "Belarus", continentId: "_Europe"},
	{iso2: "BE", name: "Belgium", continentId: "_Europe"},
	{iso2: "BZ", name: "Belize", continentId: "_North America"},
	{iso2: "BJ", name: "Benin", continentId: "_Africa"},
	{iso2: "BT", name: "Bhutan", continentId: "_Asia"},
	{iso2: "BO", name: "Bolivia", continentId: "_South America"},
	{iso2: "BA", name: "Bosnia and Herzegovina", continentId: "_Europe"},
	{iso2: "BW", name: "Botswana", continentId: "_Africa"},
	{iso2: "BR", name: "Brazil", continentId: "_South America"},
	{iso2: "BN", name: "Brunei", continentId: "_Asia"},
	{iso2: "BG", name: "Bulgaria", continentId: "_Europe"},
	{iso2: "BF", name: "Burkina Faso", continentId: "_Africa"},
	{iso2: "BI", name: "Burundi", continentId: "_Africa"},
	{iso2: "CV", name: "Cabo Verde", continentId: "_Africa"},
	{iso2: "KH", name: "Cambodia", continentId: "_Asia"},
	{iso2: "CM", name: "Cameroon", continentId: "_Africa"},
	{iso2: "CA", name: "Canada", continentId: "_North America"},
	{iso2: "CF", name: "Central African Republic", continentId: "_Africa"},
	{iso2: "TD", name: "Chad", continentId: "_Africa"},
	{iso2: "CL", name: "Chile", continentId: "_South America"},
	{iso2: "CN", name: "China", continentId: "_Asia"},
	{iso2: "TW", name: "Chinese Taipei", continentId: "_Asia"},
	{iso2: "CO", name: "Colombia", continentId: "_South America"},
	{iso2: "KM", name: "Comoros", continentId: "_Africa"},
	{iso2: "CG", name: "Congo", continentId: "_Africa"},
	{iso2: "CR", name: "Costa Rica", continentId: "_North America"},
	{iso2: "CI", name: "Côte d'Ivoire", continentId: "_Africa"},
	{iso2: "HR", name: "Croatia", continentId: "_Europe"},
	{iso2: "CU", name: "Cuba", continentId: "_North America"},
	{iso2: "CY", name: "Cyprus", continentId: "_Europe"},
	{iso2: "CZ", name: "Czech Republic", continentId: "_Europe"},
	{iso2: "KP", name: "Democratic People's Republic of Korea", continentId: "_Asia"},
	{iso2: "CD", name: "Democratic Republic of the Congo", continentId: "_Africa"},
	{iso2: "DK", name: "Denmark", continentId: "_Europe"},
	{iso2: "DJ", name: "Djibouti", continentId: "_Africa"},
	{iso2: "DM", name: "Dominica", continentId: "_North America"},
	{iso2: "DO", name: "Dominican Republic", continentId: "_North America"},
	{iso2: "EC", name: "Ecuador", continentId: "_South America"},
	{iso2: "EG", name: "Egypt", continentId: "_Africa"},
	{iso2: "SV", name: "El Salvador", continentId: "_North America"},
	{iso2: "GQ", name: "Equatorial Guinea", continentId: "_Africa"},
	{iso2: "ER", name: "Eritrea", continentId: "_Africa"},
	{iso2: "EE", name: "Estonia", continentId: "_Europe"},
	{iso2: "SZ", name: "Eswatini", continentId: "_Africa"},
	{iso2: "ET", name: "Ethiopia", continentId: "_Africa"},
	{iso2: "FM", name: "Federated States of Micronesia", continentId: "_Oceania"},
	{iso2: "FJ", name: "Fiji", continentId: "_Oceania"},
	{iso2: "FI", name: "Finland", continentId: "_Europe"},
	{iso2: "FR", name: "France", continentId: "_Europe"},
	{iso2: "GA", name: "Gabon", continentId: "_Africa"},
	{iso2: "GM", name: "Gambia", continentId: "_Africa"},
	{iso2: "GE", name: "Georgia", continentId: "_Europe"},
	{iso2: "DE", name: "Germany", continentId: "_Europe"},
	{iso2: "GH", name: "Ghana", continentId: "_Africa"},
	{iso2: "GR", name: "Greece", continentId: "_Europe"},
	{iso2: "GD", name: "Grenada", continentId: "_North America"},
	{iso2: "GT", name: "Guatemala", continentId: "_North America"},
	{iso2: "GN", name: "Guinea", continentId: "_Africa"},
	{iso2: "GW", name: "Guinea Bissau", continentId: "_Africa"},
	{iso2: "GY", name: "Guyana", continentId: "_South America"},
	{iso2: "HT", name: "Haiti", continentId: "_North America"},
	{iso2: "HN", name: "Honduras", continentId: "_North America"},
	{iso2: "HK", name: "Hong Kong, China", continentId: "_Asia"},
	{iso2: "HU", name: "Hungary", continentId: "_Europe"},
	{iso2: "IS", name: "Iceland", continentId: "_Europe"},
	{iso2: "IN", name: "India", continentId: "_Asia"},
	{iso2: "ID", name: "Indonesia", continentId: "_Asia"},
	{iso2: "IR", name: "Iran", continentId: "_Asia"},
	{iso2: "IQ", name: "Iraq", continentId: "_Asia"},
	{iso2: "IE", name: "Ireland", continentId: "_Europe"},
	{iso2: "IL", name: "Israel", continentId: "_Europe"},
	{iso2: "IT", name: "Italy", continentId: "_Europe"},
	{iso2: "JM", name: "Jamaica", continentId: "_North America"},
	{iso2: "JP", name: "Japan", continentId: "_Asia"},
	{iso2: "JO", name: "Jordan", continentId: "_Asia"},
	{iso2: "KZ", name: "Kazakhstan", continentId: "_Asia"},
	{iso2: "KE", name: "Kenya", continentId: "_Africa"},
	{iso2: "KI", name: "Kiribati", continentId: "_Oceania"},
	{iso2: "XK", name: "Kosovo", continentId: "_Europe"},
	{iso2: "KW", name: "Kuwait", continentId: "_Asia"},
	{iso2: "KG", name: "Kyrgyzstan", continentId: "_Asia"},
	{iso2: "LA", name: "Laos", continentId: "_Asia"},
	{iso2: "LV", name: "Latvia", continentId: "_Europe"},
	{iso2: "LB", name: "Lebanon", continentId: "_Asia"},
	{iso2: "LS", name: "Lesotho", continentId: "_Africa"},
	{iso2: "LR", name: "Liberia", continentId: "_Africa"},
	{iso2: "LY", name: "Libya", continentId: "_Africa"},
	{iso2: "LI", name: "Liechtenstein", continentId: "_Europe"},
	{iso2: "LT", name: "Lithuania", continentId: "_Europe"},
	{iso2: "LU", name: "Luxembourg", continentId: "_Europe"},
	{iso2: "MO", name: "Macau, China", continentId: "_Asia"},
	{iso2: "MG", name: "Madagascar", continentId: "_Africa"},
	{iso2: "MW", name: "Malawi", continentId: "_Africa"},
	{iso2: "MY", name: "Malaysia", continentId: "_Asia"},
	{iso2: "MV", name: "Maldives", continentId: "_Asia"},
	{iso2: "ML", name: "Mali", continentId: "_Africa"},
	{iso2: "MT", name: "Malta", continentId: "_Europe"},
	{iso2: "MH", name: "Marshall Islands", continentId: "_Oceania"},
	{iso2: "MR", name: "Mauritania", continentId: "_Africa"},
	{iso2: "MU", name: "Mauritius", continentId: "_Africa"},
	{iso2: "MX", name: "Mexico", continentId: "_North America"},
	{iso2: "MD", name: "Moldova", continentId: "_Europe"},
	{iso2: "MC", name: "Monaco", continentId: "_Europe"},
	{iso2: "MN", name: "Mongolia", continentId: "_Asia"},
	{iso2: "ME", name: "Montenegro", continentId: "_Europe"},
	{iso2: "MA", name: "Morocco", continentId: "_Africa"},
	{iso2: "MZ", name: "Mozambique", continentId: "_Africa"},
	{iso2: "MM", name: "Myanmar", continentId: "_Asia"},
	{iso2: "NA", name: "Namibia", continentId: "_Africa"},
	{iso2: "NR", name: "Nauru", continentId: "_Oceania"},
	{iso2: "NP", name: "Nepal", continentId: "_Asia"},
	{iso2: "NL", name: "Netherlands", continentId: "_Europe"},
	{iso2: "NZ", name: "New Zealand", continentId: "_Oceania"},
	{iso2: "NI", name: "Nicaragua", continentId: "_North America"},
	{iso2: "NE", name: "Niger", continentId: "_Africa"},
	{iso2: "NG", name: "Nigeria", continentId: "_Africa"},
	{iso2: "MK", name: "North Macedonia", continentId: "_Europe"},
	{iso2: "NO", name: "Norway", continentId: "_Europe"},
	{iso2: "OM", name: "Oman", continentId: "_Asia"},
	{iso2: "PK", name: "Pakistan", continentId: "_Asia"},
	{iso2: "PW", name: "Palau", continentId: "_Oceania"},
	{iso2: "PS", name: "Palestine", continentId: "_Asia"},
	{iso2: "PA", name: "Panama", continentId: "_North America"},
	{iso2: "PG", name: "Papua New Guinea", continentId: "_Oceania"},
	{iso2: "PY", name: "Paraguay", continentId: "_South America"},
	{iso2: "PE", name: "Peru", continentId: "_South America"},
	{iso2: "PH", name: "Philippines", continentId: "_Asia"},
	{iso2: "PL", name: "Poland", continentId: "_Europe"},
	{iso2: "PT", name: "Portugal", continentId: "_Europe"},
	{iso2: "QA", name: "Qatar", continentId: "_Asia"},
	{iso2: "KR", name: "Republic of Korea", continentId: "_Asia"},
	{iso2: "RO", name: "Romania", continentId: "_Europe"},
	{iso2: "RU", name: "Russia", continentId: "_Europe"},
	{iso2: "RW", name: "Rwanda", continentId: "_Africa"},
	{iso2: "KN", name: "Saint Kitts and Nevis", continentId: "_North America"},
	{iso2: "LC", name: "Saint Lucia", continentId: "_North America"},
	{iso2: "VC", name: "Saint Vincent and the Grenadines", continentId: "_North America"},
	{iso2: "WS", name: "Samoa", continentId: "_Oceania"},
	{iso2: "SM", name: "San Marino", continentId: "_Europe"},
	{iso2: "ST", name: "São Tomé and Príncipe", continentId: "_Africa"},
	{iso2: "SA", name: "Saudi Arabia", continentId: "_Asia"},
	{iso2: "SN", name: "Senegal", continentId: "_Africa"},
	{iso2: "RS", name: "Serbia", continentId: "_Europe"},
	{iso2: "SC", name: "Seychelles", continentId: "_Africa"},
	{iso2: "SL", name: "Sierra Leone", continentId: "_Africa"},
	{iso2: "SG", name: "Singapore", continentId: "_Asia"},
	{iso2: "SK", name: "Slovakia", continentId: "_Europe"},
	{iso2: "SI", name: "Slovenia", continentId: "_Europe"},
	{iso2: "SB", name: "Solomon Islands", continentId: "_Oceania"},
	{iso2: "SO", name: "Somalia", continentId: "_Africa"},
	{iso2: "ZA", name: "South Africa", continentId: "_Africa"},
	{iso2: "SS", name: "South Sudan", continentId: "_Africa"},
	{iso2: "ES", name: "Spain", continentId: "_Europe"},
	{iso2: "LK", name: "Sri Lanka", continentId: "_Asia"},
	{iso2: "SD", name: "Sudan", continentId: "_Africa"},
	{iso2: "SR", name: "Suriname", continentId: "_South America"},
	{iso2: "SE", name: "Sweden", continentId: "_Europe"},
	{iso2: "CH", name: "Switzerland", continentId: "_Europe"},
	{iso2: "SY", name: "Syria", continentId: "_Asia"},
	{iso2: "TJ", name: "Tajikistan", continentId: "_Asia"},
	{iso2: "TZ", name: "Tanzania", continentId: "_Africa"},
	{iso2: "TH", name: "Thailand", continentId: "_Asia"},
	{iso2: "TL", name: "Timor-Leste", continentId: "_Asia"},
	{iso2: "TG", name: "Togo", continentId: "_Africa"},
	{iso2: "TO", name: "Tonga", continentId: "_Oceania"},
	{iso2: "TT", name: "Trinidad and Tobago", continentId: "_North America"},
	{iso2: "TN", name: "Tunisia", continentId: "_Africa"},
	{iso2: "TR", name: "Turkey", continentId: "_Europe"},
	{iso2: "TM", name: "Turkmenistan", continentId: "_Asia"},
	{iso2: "TV", name: "Tuvalu", continentId: "_Oceania"},
	{iso2: "UG", name: "Uganda", continentId: "_Africa"},
	{iso2: "UA", name: "Ukraine", continentId: "_Europe"},
	{iso2: "AE", name: "United Arab Emirates", continentId: "_Asia"},
	{iso2: "GB", name: "United Kingdom", continentId: "_Europe"},
	{iso2: "US", name: "United States", continentId: "_North America"},
	{iso2: "UY", name: "Uruguay", continentId: "_South America"},
	{iso2: "UZ", name: "Uzbekistan", continentId: "_Asia"},
	{iso2: "VU", name: "Vanuatu", continentId: "_Oceania"},
	{iso2: "VA", name: "Vatican City", continentId: "_Europe"},
	{iso2: "VE", name: "Venezuela", continentId: "_South America"},
	{iso2: "VN", name: "Vietnam", continentId: "_Asia"},
	{iso2: "YE", name: "Yemen", continentId: "_Asia"},
	{iso2: "ZM", name: "Zambia", continentId: "_Africa"},
	{iso2: "ZW", name: "Zimbabwe", continentId: "_Africa"},
];

// iso2 -> continentId, derived from WCA_COUNTRIES at module load.
export const COUNTRY_TO_CONTINENT: Record<string, string> = WCA_COUNTRIES.reduce(
	(acc, c) => {
		acc[c.iso2] = c.continentId;
		return acc;
	},
	{} as Record<string, string>,
);
