default_platform(:ios)

TEAM_ID = "R6CCJB68TQ"
APP_IDENTIFIER = "com.zktimer.app"
APPLE_ID = "ibrhyyme@icloud.com"
ASC_APP_ID = "11492926306"

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    cocoapods(podfile: "./Podfile")

    cert(
      team_id: TEAM_ID,
      username: APPLE_ID
    )

    sigh(
      app_identifier: APP_IDENTIFIER,
      team_id: TEAM_ID,
      username: APPLE_ID,
      force: true
    )

    latest_build = latest_testflight_build_number(
      app_identifier: APP_IDENTIFIER,
      username: APPLE_ID,
      team_id: TEAM_ID,
      initial_build_number: 0
    )
    increment_build_number(
      xcodeproj: "App.xcodeproj",
      build_number: latest_build + 1
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      clean: true,
      xcargs: "DEVELOPMENT_TEAM=#{TEAM_ID} CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=\"#{ENV['SIGH_NAME'] || "match AppStore #{APP_IDENTIFIER}"}\""
    )

    upload_to_testflight(
      apple_id: ASC_APP_ID,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
