default_platform(:android)

PACKAGE_NAME = "com.zktimer.app"

platform :android do
  desc "Build and upload to Play Store Internal Track"
  lane :beta do
    json_key_path = ENV["PLAY_STORE_JSON_KEY_PATH"]

    gradle(
      task: "clean bundleRelease",
      project_dir: ".",
      properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"]
      }
    )

    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      json_key: json_key_path,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
