name: ZKTimer Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GCP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ibrahimyldz77/Zkt-Timer
          
          # 1. Kodları çek
          git pull origin main
          
          # 2. Konteynerleri başlat (Gerekirse)
          docker-compose up -d
          
          # 3. ŞİMDİ SİHİR BURADA:
          # "DEPLOYING=true" diyerek ona "Sadece pişir ve kapat, beni bekleme" diyoruz.
          echo "Kek fırına veriliyor (Build işlemi)..."
          docker exec -e DEPLOYING=true zkt-timer_app_1 yarn build
          
          # 4. Yeni dosyalarla servisi tazele
          docker restart zkt-timer_app_1